---
baseurl: "https://www.runto.lv/"
languageCode: "zh-cn"
DefaultContentLanguage: "zh-cn"
title: "Runto's Blog"
theme: "hugo-theme-learn"
canonifyURLs: true
params:
  editURL: "https://github.com/runto-lv/blog-doc/edit/master/content/"
  showVisitedLinks: true
  disableShortcutsTitle: false
outputs:
  home: 
    - HTML
    - RSS 
    - JSON
    - Algolia
outputFormats:
  Algolia:
    baseName: "algolia"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true
